import LayoutDashboard from '@/layouts/HeaderDashboard'
import Head from 'next/head'
import React from 'react'

export default function Page() {
  return (
    <>
      <Head >
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Dashboard</div>
    </>
  )
}

Page.getLayout = function getLayout(page: React.ReactElement) {
  return (
    <LayoutDashboard>
      {page}
    </LayoutDashboard>
  )
}