import { GridPages0 } from '@/components/grid/ListPages0'
import LayoutDashboard from '@/layouts/HeaderDashboard'
import { getPortfolioPages0WithCursor } from '@/lib/pages/page0/read'
import { PaginationProvider } from '@/providers/PaginationContext'
import { dehydrate, QueryClient } from '@tanstack/react-query'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import React from 'react'

export default function Page() {
  return (
    <>
      <Head >
        <title>Pages | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PaginationProvider>
        <GridPages0/>
      </PaginationProvider>
    </>
  )
}

Page.getLayout = function getLayout(page: React.ReactElement) {
  return (
    <LayoutDashboard>
      {page}
    </LayoutDashboard>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(
    ["portfolio-get-pages0-with-cursor", { first: 256 }, process.env.NEXT_PUBLIC_SITE_URL as string],
    async () =>
    getPortfolioPages0WithCursor(
        { first: 256 },
        process.env.NEXT_PUBLIC_SITE_URL as string
      )
  );
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
      revalidate: 86400,
    },
  };
};
